services:
  go-service:
    container_name: go-service
    # build: .
    image: golang:1.22.0-alpine
    tty: true
    working_dir: /code
    restart: always
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - .:/code

  auth-proxy:
    container_name: auth-proxy
    # image: auth-proxy-img
    build: ../../auth-proxy/feat-auth-proxy
    tty: true
    restart: always
    ports:
      - "4300:4300"
    env_file:
      - .env.auth


  # client:
  #   container_name: client
  #   image: vsud/ev-game:client-2.1.1
  #   tty: true
  #   restart: always
  #   ports:
  #     - "3300:3300"

  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    container_name: admin
    image: adminer
    restart: always
    ports:
      - 5555:8080

volumes:
  pgdata:
