export const initialVotes = {
	armenia: null,
	australia: null,
	azerbaijan: null,
	belgium: null,
	czech_republic: null,
	estonia: null,
	finland: null,
	france: null,
	germany: null,
	greece: null,
	iceland: null,
	italy: null,
	lithuania: null,
	moldova: null,
	netherlands: null,
	norway: null,
	poland: null,
	portugal: null,
	romania: null,
	serbia: null,
	spain: null,
	sweden: null,
	switzerland: null,
	ukraine: null,
	united_kingdom: null,
};
