export interface IGetVotesResponse {
	_id: string;
	username: string;
	armenia: string;
	australia: string;
	azerbaijan: string;
	belgium: string;
	czech_republic: string;
	estonia: string;
	finland: string;
	france: string;
	germany: string;
	greece: string;
	iceland: string;
	italy: string;
	lithuania: string;
	moldova: string;
	netherlands: string;
	norway: string;
	poland: string;
	portugal: string;
	romania: string;
	serbia: string;
	spain: string;
	sweden: string;
	switzerland: string;
	ukraine: string;
	united_kingdom: string;
}
