export enum CountryTypes {
	UKRAINE = "ukraine",
	UNITED_KINGDOM = "united_kingdom",
	SPAIN = "spain",
	SWEDEN = "sweden",
	SERBIA = "serbia",
	NORWAY = "norway",
	BELGIUM = "belgium",
	CZECH_REPUBLIC = "czech_republic",
	ROMANIA = "romania",
	PORTUGAL = "portugal",
	FINLAND = "finland",
	SWITZERLAND = "switzerland",
	FRANCE = "france",
	ARMENIA = "armenia",
	ITALY = "italy",
	NETHERLANDS = "netherlands",
	GERMANY = "germany",
	LITHUANIA = "lithuania",
	AZERBAIJAN = "azerbaijan",
	GREECE = "greece",
	ICELAND = "iceland",
	MOLDOVA = "moldova",
	AUSTRALIA = "australia",
	POLAND = "poland",
	ESTONIA = "estonia",
}
